### PR TITLE
Review of guides + further setup of website

### PR DESCRIPTION
**Pull request by peterdesmet**
This pull request is still active, don't merge yet. Todo:

- [x] Add bootstrap classes to content https://github.com/tdwg/tdwg-theme/issues/24

## Simple guide

- [x] Review header section
- [x] Review headings
- [x] Fix section references
- [x] Use `inline code` rather than _italic_
- [x] Review code blocks
- [x] Stop using CAPITAL links (e.g. TEXTGUIDE)
- [x] Verify images and tables

## XML guide

- [x] Review header section
- [x] Review headings
- [x] Fix section references
- [x] Use `inline code` rather than _italic_
- [x] Review code blocks
- [x] Stop using CAPITAL links (e.g. TEXTGUIDE)
- [x] Verify images and tables

## RDF guide

- [x] Review header section
- [x] Review headings
- [x] Fix section references
- [x] Use `inline code` rather than _italic_
- [x] Review code blocks
- [x] Stop using CAPITAL links (e.g. TEXTGUIDE)
- [ ] Verify images and tables
- [x] Verify footnotes

## Text guide

- [x] Review header section
- [x] Review headings
- [x] Fix section references
- [x] Use `inline code` rather than _italic_
- [x] Review code blocks
- [x] Stop using CAPITAL links (e.g. TEXTGUIDE)
- [x] Verify images and tables

### CODE REVIEW

**Comment by peterdesmet** [comment]
Broken links:

- Text guide: `../text/example_text_simpledwc_complete.xml`

**Comment by baskaufs** [comment]
See also https://github.com/tdwg/rs.tdwg.org/issues/14

**Comment by peterdesmet** [comment]
@baskaufs Thanks for pointing this out, corrected in a9c3668f0170e974ddac3e057444f8635f65dab7

While we're add it, the footer should contain copyright statement + license. Would the one from the TDWG website suffice:

> Content on this site, made open by Biodiversity Information Standards (TDWG) is licensed under a Creative Commons Attribution 4.0 International License.

And if you have a chance, can you have a look at the correctness of the header sections? See http://peterdesmet.com/dwc/simple/ and the 3 other guides

**Comment by baskaufs** [comment]
As far as the copyright statement is concerned, I think that's probably fine.  I believe that I heard that the default license is CC BY 4.0 international.

I'll look at the headers.  it's on my todo list.

**Comment by baskaufs** [comment]
OK, I've made a bunch of edits at https://github.com/baskaufs/dwc/tree/master/docs .  I'm done with the headers (mostly) but the RDF guide is taking forever.  Questions:
- Did we decide how to include contributors in the recommended bibliographic citation?  The "author" is supposed to be the task group, but it still seems like the contributors should be there somewhere.  
- In titles, do we want all key words to be capitalized?  I followed what you had (not all capitalized) but it's looking kind of weird to me.  I don't really care that much, just so we are consistent.

**Comment by baskaufs** [comment]
Oh, also all of the footnotes appear to be broken in the RDF guide.  Did we have an example of how to fix that?

**Comment by baskaufs** [comment]
Oh, one more thing.  This page:
https://code.google.com/archive/p/tdwg-rdf/wikis/DwCAncillary.wiki
is referenced a bunch of times.  It's broken at Google Code, but I can fix it and put it somewhere in the Github repo.  But where should it go in the repo structure?  Somewhere within docs, I suppose...

**Comment by peterdesmet** [comment]
Yes, single ticks for inline code, triple ticks (or 4 spaces, but rather not) for code blocks. I'll see if I can fix the footnotes.

**Comment by peterdesmet** [comment]
@baskaufs the tables that are unchecked below break out of the container of the page (just Ctrl + F their name on http://peterdesmet.com/dwc/rdf/):

- [x] Table 1
- [x] Table 2
- [ ] Table 3
- [ ] Table 4
- [ ] Table 5
- [x] Table 6
- [ ] Table 7
- [ ] Table 8
- [ ] Table 9: especially bad
- [x] Table 10

I wonder if we should leave them as is, or try to transpose them (switching rows for columns) so they are more readable?

**Comment by peterdesmet** [comment]
Footnotes fixed in cc71250, only the tables remain.

**Comment by peterdesmet** [comment]
Thanks for merging @stanblum, but just a bit too soon. 😂 I still have some commits lined up that I will send in another PR.

**Comment by stanblum** [comment]
I couldn't really tell what was going on there.  Multiple pull requests on
series of commits on a single file?

**Pull request merged**
