### PR TITLE
Review 2023

### PR DESCRIPTION
**Pull request by baskaufs**
I've completed running the changes through the pipeline using the actual ratification date of 2023-06-28 as the version date for everything. After examining the diffs carefully, it appears to me that everything is OK.

@tucotuco Please scan through the diffs and check the ordering in the QRG carefully. I believe that I extracted the order that you had in your term versions draft and put it into `qrg-list.csv` correctly. The new terms appear in reasonable places in the QRG. If they aren't right, then just correct the order in `qrg-list.csv`, then re-run the `generate_term_versions.py` and `build.py` scripts again. That should fix any issues with ordering.

I have not yet created the release of the rs.tdwg.org repo that will trigger the dereferencing of the new terms to go live. When this has been merged, ping me and I'll do that release. I think we will also want to do an new release here once we've assured ourselves that everything is as it should be.

### CODE REVIEW

**Comment by baskaufs** [comment]
@tucotuco Actually, hold off on merging this. I forgot to update the Decision History and the List of Terms doc needs that to insert the relevant decision into the term metadata. I will probably wait until tomorrow morning to do it since I'm out of energy for tonight. I will ping you when it's done.

**Comment by baskaufs** [comment]
@tucotuco I went ahead and fixed the Decision history issue. So I'm done and I think you can move forward when you are ready.

**Comment by peterdesmet** [comment]
Thanks Steve for doing all this!

**Comment by baskaufs** [comment]
@tucotuco OK, I think everything is in place now if you want to give it another look.

**Comment by tucotuco** [comment]
Looks good at a glance. The easiest way to check fully is in production. I
think we're ready for that.  Thanks!

**Comment by baskaufs** [comment]
@tucotuco Should we merge? It's currently blocked pending an approving review (unless I bypass the branch protections).

**Review by tucotuco — APPROVED** [review]

**Review by tucotuco — APPROVED** [review]

**Review by tucotuco — APPROVED** [review]

**Comment by tucotuco** [comment]
Merged.

**Pull request merged**
