### PR TITLE
Complete issue 265

### PR DESCRIPTION
**Pull request by baskaufs**
This is an attempt to address checkbox 3 of https://github.com/tdwg/dwc/issues/265 . There were a couple other corrections that I also made.

One thing that I don't know how to address is making the [list of terms document](https://dwc.tdwg.org/list/) show up in the TDWG bar at the top of the page. That should probably be revised, changing "Terms" to "Quick Reference" and adding something like "Term list" for the new list of terms document.

### CODE REVIEW

**Comment by baskaufs** [comment]
After this gets merged, I think the build script for the QRG actually needs to be run and pushed to make the updates live.

**Comment by baskaufs** [comment]
@tucotuco @peterdesmet Should the list of terms document have text about the QRG and a link? People can see it in the header, but I'm thinking that it should. See also https://github.com/tdwg/website/pull/165

**Comment by tucotuco** [comment]
Yes, I think it would be good.

**Comment by baskaufs** [comment]
How's this for the link from the list of terms to the QRG: https://github.com/tdwg/dwc/pull/272/commits/b01b1ad6b276f1113f1fd5cf3a7c0cdeda10b904 ?

**Comment by baskaufs** [comment]
@peterdesmet Are you good with this? To summarize:
- a link was added from the QRG to the new list of terms document https://github.com/tdwg/dwc/pull/272/commits/8b9c956400278878449e66b1e9ff5ebd977f432d **Please check that [the relative link to the list of terms document was done correctly (`list/`)](https://github.com/tdwg/dwc/blob/complete_issue_265/build/terms.tmpl#L11)**
- a link was added from the DwC GitHub repo readme to the new list of terms document https://github.com/tdwg/dwc/pull/272/commits/90b42ab46198e6aaead66ca00f3e777aec41561b
- a link was added from the list of term document to the QRG https://github.com/tdwg/dwc/pull/272/commits/b01b1ad6b276f1113f1fd5cf3a7c0cdeda10b904
- changed Baskauf affiliation https://github.com/tdwg/dwc/pull/272/commits/3ebeb8894fe123541de19ab653c53822696f02cf

After merging, the QRG needs to be rebuilt and pushed to GitHub.

I believe that this is all that remains for completing the [Implement sustainable vocabulary maintenance workflow milestone](https://github.com/tdwg/dwc/milestone/10).

**Comment by tucotuco** [comment]
Yay! So close!

**Review by peterdesmet — APPROVED** [review]
Nice!
I have corrected the link to `../list/`.
I have also changed 3 absolute dwc.tdwg.org links to relative links
And resolved a conflict for your affiliation (Vanderbilt University vs Vanderbilt University Libraries). This branch had the latter, so choose that.

**Comment by peterdesmet** [comment]
I noticed some 2020-08-12 terms, should we rebuild?

**Comment by tucotuco** [comment]
> I noticed some 2020-08-12 terms, should we rebuild?

Yes, please.

**Comment by baskaufs** [comment]
See https://github.com/tdwg/dwc/pull/277 for rebuilt `term_versions.csv`. After running `build.py` I think the QRG should be in synch with the [list of terms document](https://dwc.tdwg.org/list/) since it has already been updated to the 2020-08-12 version.

**Pull request merged**
