### PR TITLE
Implement changes to "normative document" discussed at DwC MG meeting

### PR DESCRIPTION
**Pull request by baskaufs**
This branch includes a number of changes that were discussed during and after recent DwC Maintenance Group meeting. It needs to be checked to see what effects the changes have on the Quick Reference Guide. The most obvious thing is that the labels were reverted from camelCase to English prose. This change will definitely have an effect on the QRG unless the script is changed to use the term local names. So it should not be merged until that particular issue is resolved.

The changes involving `dcterms:language` and `dcterms:type` should also be looked at carefully. The intent is that `dc:language` should replace `dcterms:language` in the record-level terms section, `dc:type` should replace `dcterms:type` in the record-level terms section, `dcterms:language` should move into the UseWithIRI section, and `dcterms:type` should disappear from the QRG (since the DwC RDF Guide says that `rdf:type` should be used instead of it in the case where one desires to indicate type by an IRI).

If these changes are appropriate, I'll use it as the standard to check whether [build script 3](https://github.com/tdwg/dwc/issues/251) will faithfully generate the file necessary to build the QRG. That can be done before a merge as long as I know that this is ultimately the form we want the "normative document" to take.

This pull request is related to the following issues:

- [253 human-readable labels](https://github.com/tdwg/dwc/issues/253)
- [255 simple/extension flags](https://github.com/tdwg/dwc/issues/255)
- [checkbox 2 of 252: technical changes involving `dc:/dcterms:language` and `type`](https://github.com/tdwg/dwc/issues/252)
- [checkbox 3 of 252: restoring legacy `dwc:accordingTo` term history (deprecated)](https://github.com/tdwg/dwc/issues/252)
- [alphabetize non-recommended term version IRIs (discussed in 256)](https://github.com/tdwg/dwc/issues/256)

### CODE REVIEW

**Comment by baskaufs** [comment]
I forgot several technical changes related to the `replaces` column for DCMI borrowed terms. See the commit notes for details.

**Comment by baskaufs** [comment]
Just to let you know where I am on this: I've run the 2017 and 2018 changes through the build script and am now comparing the diffs of the term_version.csv file in this pull request with the generated one. I'm determining whether the difference is something that I missed in this branch's version or if it is a problem with the source data in the rs.tdwg.org that the build script is using. There are a bunch of camelCase/prose differences I need to reconcile, but I think I'm close to getting it right with the build script.

**Comment by peterdesmet** [comment]
@baskaufs indeed, the QRG build script now spits out the English labels (like `Institution ID`). I'm assuming you have a `term_localName` in your source CSV? And you're not adding this to `term_versions.csv` because it wouldn't allow you to do git diff checks?

Can you also generate a term_versions_localName.csv with that `term_localName` added? I'm suggesting with `term_localName` as second column, right after `iri`.

**Comment by baskaufs** [comment]
@peterdesmet Yes, that is correct. I can easily add the term_localname column as the second column right after iri. And yes, I'm going through every diff that I see and either changing the source rs.tdwg.org data (if I think it's wrong) or the draft term_versions.csv (if I think it is wrong). I will keep going until there are no diffs and then consider the build script to be fully working. 

So you can operate on the assumption that there will be a term_localname column - I will add it as the last thing.

**Comment by baskaufs** [comment]
@tucotuco One of the major diffs that I have is that the abcdEquivalence values have been removed from all of the obsolete terms (curatorial, digr.org terms, etc.) in term_versions.csv . I still have those values in rs.tdwg.org. I could remove them from the rs.tdwg.org source files, but that seems like a bad idea since it would be throwing away historical information. I'm not sure why it hurts to have that information in the term_versions.csv file since nobody will probably ever care or look at it and it has no effect on building the QRG. Let me know what you want me to do. I'm going to have to stop working on this for a while, so I'll just wait until you give me an answer on this before proceeding.

**Comment by tucotuco** [comment]
I don't know how those equivalents were lost, truthfully. It surely was not
intended. So if you can add them back again, that would be great.

**Comment by baskaufs** [comment]
OK, so I think I'm done with this. 

I've harmonized the data that is coming out of the rs.tdwg.org repo with the normative document so that all recommended terms in the script-generated term_versions.csv file are identical to the term_versions.csv file that was hand-edited in all of the commits listed above. I think that I've justified all of the changes that I made in the commit comments - in some cases I restored metadata that had gone missing and in other cases I corrected erroneous metadata, such as suggesting literal value examples for `dwciri:` terms. So the only changes that will be happening in the Quick Reference Guide are either error corrections or things we discussed at the meeting.

The non-recommended terms are another story. I finally got them all sorted out so that I could compare the diffs on a term-by-term basis, but there are literally dozens of differences. Some of them are relatively minor, caused by things like retroactively adding backticks to a bunch of the old examples. But there are others that don't make sense, like terms in the term_versions.csv file that say they replace themselves and comments from recent versions being found in much older versions. I am suspicious that most of these differences were introduced in the past by hand-editing of the term_versions.csv . I went through the version history and found where some of them were introduced, but it was just too much work to track them all down. I believe that we should just go with the historical versions from the rs.tdwg.org source and forget about the ones currently present in term_versions.csv . The rs.tdwg.org version history came directly from the original DwC history XML file with virtually no editing, so I think it is fair to consider it the actual term history.

If you agree with what I've said here, then we might be close to being ready for a merge. The `dcmi-term-changes` branch now contains three files. `term_versions-old.csv` is the morphed version that came from the prior term_versions.csv file via all of the commits. Once we go through with this, it can be deleted and just live in the version history. `term_versions.csv` is the version generated by the build script from rs.tdwg.org (well from a branch of rs.tdwg.org that I need to merge before we are done). That file should be tested using the existing Quick Reference Guide build script to make sure that the QRG it generates is good. The `generated_normative_document.csv` file is the same as `term_versions.csv` except that it has the additional column that @peterdesmet requested: `term_localName` as the second column immediately after the `iri` column. This is the version that ultimately should be used once the QRG build script is modified to use it.

So what needs to happen is: 
- [ ] agree that the series of commits that I've made are correct/acceptable.
- [ ] test the `term_versions.csv` file with the QRG build script to make sure that it produces correct results. Those results should be the same as the results produced by running the `term_versions-old.csv` file through the QRG build script.
- [ ] delete the `term_versions-old.csv` file, which would no longer be relevant.
- [ ] modify the QRG build script to use the extra column in the `generated_normative_document.csv` file so that it makes the labels appear on the QRG as desired. Once that is done, it can replace the `term_versions.csv` file and this branch can be merged with the master. 
- [ ] move the script that builds the `term_versions.csv` file from <https://github.com/baskaufs/msc/blob/master/dwc_workflow/generate_normative_csv.ipynb> to some appropriate place in the DwC repo. There are a few path changes that will have to be made in the script Jupyter notebook. Once I merge the changes I've made to the rs.tdwg.org repo, the value of `github_baseUri` will need to be changed to the master branch. At the end of the script, the save file path will need to be changed from `generated_normative_document.csv` to `term_versions.csv` with an appropriate relative path so that the file will end up in the right place relative to where the script is stashed.

**Comment by peterdesmet** [comment]
Steve, I agree with the series of commits you have made.

I have just ran the `term_versions.csv` on this branch through build script and these are the changes. @baskaufs can you check off those that are expected and look into those that are not?

- [ ] All labels are human readable
- [ ] `dcterms:type` now `dc:Type`, with url changed from `http://purl.org/dc/terms/type` to `http://purl.org/dc/elements/1.1/type`
- [ ] `dcterms:language` now `dc:Language`, with url changed from `http://purl.org/dc/terms/language` to `http://purl.org/dc/elements/1.1/language` and comments from `Recommended best practice is to use RFC 5646 as a controlled vocabulary.` to `Recommended best practice is to use RFC 5646 as a controlled vocabulary.`
- [ ] `accessRights` has the following moved from definition to comments: `Access Rights may include information regarding access or restrictions based on privacy, security, or other policies.`
- [ ] `dcterms:Language`: new term listed under `dwciri`
- [ ] `Geodetic Datum (IRI)`: `https://epsg.io/4326` wrapped in backticks
- [ ] `Organism Quantity Type (IRI)`: `A dwc;organismQuantityType ...` corrected to `A dwc:organismQuantityType ...`
- [ ] `Sampling Size Unit (IRI)`: examples were `<code>minute</code>, <code>hour</code>, <code>day</code>, <code>metre</code>, <code>square metre</code>, <code>cubic metre</code>` but those are now empty
- [ ] `Verbatim SRS (IRI)`: definition changed from `Recommended best practice is to use an IRI for the EPSG code of the SRS, if known. Otherwise use an IRI or controlled vocabulary for the name or code of the geodetic datum, if known. Otherwise use an IRI or controlled vocabulary for the name or code of the ellipsoid, if known. If none of these is known, use the value <code>unknown</code>.` to `Recommended best practice is to use an IRI for the EPSG code of the SRS, if known. Otherwise use a controlled vocabulary IRI for the name or code of the geodetic datum, if known. Otherwise use a controlled vocabulary IRI for the name or code of the ellipsoid, if known.` and examples from `<code>EPSG:4326</code>, <code>WGS84</code>, <code>NAD27</code>, <code>Campo Inchauspe</code>, <code>European 1950</code>, <code>Clarke 1866</code>, <code>unknown</code>` to empty
- [ ] `According To` property is listed at very end of QRG

**Comment by baskaufs** [comment]
Response to check-offs:

1. It is expected that the the labels would become human-readable since the values in the `label` column were reverted to human-readable from local names. I'm assuming that the new column `term_localName` would be used in the QRG to present the local names instead of the human-readable labels. I think that was what we were talking about to keep the appearance of the QRG the same as what people were used to.
2. In the second checkbox item, you said `dc:Type`. Was that a typo - it should be `dc:type` (no uppercase). Otherwise, that is expected.
3. dwc:accordingTo was included because it's status was "recommended" rather than deprecated. Although I don't think there was ever a decision to get rid of it, it was never really used for anything and is only a historical curiosity. So I have changed its status to "deprecated" and re-run the script. So I think it should no longer show up in the QRG.

**Comment by tucotuco** [comment]
This all looks good to me. Is it OK to merge?

**Comment by baskaufs** [comment]
When @tucotuco agrees that the series of commits are OK, the first box can be ticked and I will go ahead with merging https://github.com/tdwg/rs.tdwg.org/pull/38, which I think is the only thing blocking https://github.com/tdwg/dwc/issues/256 . 

The next steps are for @peterdesmet to decide what changes need to be made in the QRG build script. First, whether to make it work without the `tdwgutility:UseWithIRI` row or save that for later (I think the last thing blocking https://github.com/tdwg/dwc/issues/252) and second whether to make the script use the new term_localName column instead of the label column or whether to just leave the label column as it currently is (with the localNames instead of English prose) for now. That's one of the remaining checkboxes blocking this issue.

**Comment by baskaufs** [comment]
@tucotuco I think there are still some boxes to tick before merging

**Comment by baskaufs** [comment]
The script that builds `term_versions.csv` from the data in the rs.tdwg.org repo is now in the `build` directory. It currently outputs the file into that directory, but could be changed to put it in a different path.  https://github.com/tdwg/dwc/commit/665ca08d538fde5689c2c405e9b35c53a1d36e34#diff-19d84221e53d6c43dde26fcaa8d1e180

**Comment by peterdesmet** [comment]
- `accordingTo` is indeed removed now
- Let's leave `tdwgutility:UseWithIRI` in for now. @baskaufs Maybe it can be logged as a separate issue, so that #252 can be closed?
- the build script has been adapted to work from `generated_normative_document.csv` and use `term_localName` as label. 5aa48c8

@baskaufs, you can:

- Rename `build/generate_normative_csv.py` to `build/generate_term_versions.py` (a suggestion)
- Rename `generated_normative_document.csv` to `term_versions.csv` (effectively replacing it) in your script as well the output.

Once that is done, I will revert the build script to work from that file again and we can merge.

**Comment by baskaufs** [comment]
@peterdesmet I have renamed the script as you suggested. I also added a source file that I had forgotten (`qrg-list.csv`) that is used by the script to determine the order of the terms in the Quick Reference Guide. I deleted `generated_normative_document.csv` and ran the script to generate the replacement `term_versions.csv` (now with the term_localName column). The diff (https://github.com/tdwg/dwc/commit/1d52ee818dd315b8595c8bf3824d9451c719f1c5#diff-7af473e1d078337b36d73b11b0780a48) seems to indicate that the generated file is as designed. But you might try building the QRG from it one more time to make sure that all is well. 

I think that when you can verify that the built QRG is OK we would be ready to merge.

**Comment by baskaufs** [comment]
Checking off the box for "modify the QRG build script to use the extra column in the generated_normative_document.csv file so that it makes the labels appear on the QRG as desired. Once that is done, it can replace the term_versions.csv file and this branch can be merged with the master." because it was done in https://github.com/tdwg/dwc/pull/264/commits/5aa48c8a4f11aefd507f7bbe842cde858c4d8279

**Comment by baskaufs** [comment]
Checking off the box for "move the script that builds the term_versions.csv file from https://github.com/baskaufs/msc/blob/master/dwc_workflow/generate_normative_csv.ipynb to some appropriate place in the DwC repo. There are a few path changes that will have to be made in the script Jupyter notebook. Once I merge the changes I've made to the rs.tdwg.org repo, the value of github_baseUri will need to be changed to the master branch. At the end of the script, the save file path will need to be changed from generated_normative_document.csv to term_versions.csv with an appropriate relative path so that the file will end up in the right place relative to where the script is stashed." because it was done in https://github.com/tdwg/dwc/pull/264/commits/665ca08d538fde5689c2c405e9b35c53a1d36e34

**Comment by baskaufs** [comment]
In https://github.com/tdwg/dwc/pull/264/commits/b16d8931a1a7f9eca8fbc568e387bed74a2f2f32 I have moved the Jupyter notebook that generates the list of terms document to the `build` directory along with the header and footer templates that it uses. I also modified the header template to match the other DwC documents like the RDF guide, etc. so hopefully it will render the same way.  I also added a few notes to the README.md about this in https://github.com/tdwg/dwc/pull/264/commits/00578209eb9ae90f502ef4d2b3b0d2e736b29f84

Todo:
- [ ] Check that the page renders appropriately using the TDWG template (especially the backtics in the example fields).
- [ ] Following the patterns of the other documents like the guides, the URL should end in `/list/`. If this is not correct, then the directory structure should be changed appropriately and the build script save location changed.
- [ ] Once the URL is settled, a link needs to be added to the list of terms from the QRG, with appropriate text explaining what it is.

**Comment by baskaufs** [comment]
@tucotuco @peterdesmet The link to the updated list of terms document is [here](https://github.com/tdwg/dwc/blob/dcmi-term-changes/docs/list/index.md). I believe that it now includes all of the changes @tucotuco made and those terms are versioned using today's date.

**Comment by peterdesmet** [comment]
Hi @baskaufs, the `build.py` script now uses `term_versions.csv` again and works fine.

The `docs/list/index.md` renders ok for the most part:

- [ ] It is correct that `dcterms:Location` is the only class not starting with `dwc:`?
- [ ] Is the capitalization on `dwc_DwCType` correct?
- [ ] All term links point to URLs such as `.../list/#dwc_organismQuantityType`
- [ ] There are trailing `</tr>` tags before every vocabulary element. I think this is caused by a missing `<tr>` before modified.

Screenshot 2020-08-13 at 10 20 06

- [ ] The backticks are not rendered properly, because markdown _in_ html (here: a table) is just displayed as play text. You need to convert these to html yourself in the notebook. We also had to do this in the QRG build script. For now, I'd say: leave as is or copy/paste from this function: https://github.com/tdwg/dwc/blob/67e30c9ac039f16dbe8ecb4ffd9cc103d0699672/build/build.py#L156-L161 The same applies to http links: https://github.com/tdwg/dwc/blob/67e30c9ac039f16dbe8ecb4ffd9cc103d0699672/build/build.py#L163-L174

**Comment by baskaufs** [comment]
@peterdesmet 

checkbox 1: Yes, only `dcterms:Location`.

checkbox 2: John might know the history of `dwc:DwCType`. As far as I know, it is a historical anomaly that is only included here because it was in the `dwc:` namespace in the past and was part of the original `dwchistory` RDF/XML file that was the source of all of the historical information. It is the only term that has the type `dcam:VocabularyEncodingScheme` and I have no idea what the conventions are for capitalization of that.

checkbox 3: Not sure what the problem is here. Are you talking about the links in the index? The page source shows them as pointing to local fragment identifiers:



and they link to other places in the document as designed:



Am I misunderstanding something?

checkbox 4: I'm not seeing this problem either. In the page source, the `<tr>` in front of `<td>Modified</td>` is indented in a "non-pretty" way and lacks a hard return after it, but it is there. 

```
	<tbody>
		<tr>
			<td>Term IRI</td>
			<td><a href="http://rs.tdwg.org/dwc/terms/acceptedNameUsage" rel="nofollow">http://rs.tdwg.org/dwc/terms/acceptedNameUsage</a></td>
		</tr>
			<tr><td>Modified</td>
			<td>2017-10-06</td>
		</tr>
		<tr>
			<td>Term version IRI</td>
			<td><a href="http://rs.tdwg.org/dwc/terms/version/acceptedNameUsage-2017-10-06" rel="nofollow">http://rs.tdwg.org/dwc/terms/version/acceptedNameUsage-2017-10-06</a></td>
		</tr>
...
	</tbody>
```

I tried putting the HTML in Oxygen to validate it, but there are a lot of problems caused by the backticks mixed with Jekyll's automatic hyperlinking. So it's hard to identify problems with the HTML until that is fixed.

checkbox 5: 

I would like to fix this, but I'm running out of time to work on this project now. So if it's "good enough" for now, I guess I would be OK with fixing it later. I'll create an issue, assign it to me and try to get to it before too much time goes by.

**Comment by peterdesmet** [comment]
Checkbox 3: no misunderstanding, links seem ok
Checkbox 4: odd, let's fix this later: https://github.com/tdwg/dwc/issues/270
Checkbox 5: minor thing, having separate issue is ok

**Comment by tucotuco** [comment]
Just an FYI. dwc:DwCType is correct. It was a term parallel to dc:type, but for the basisOfRecord vocabulary. All history.

**Pull request merged**
