### PR TITLE
Fix list of terms build script

### PR DESCRIPTION
**Pull request by baskaufs**
@peterdesmet I think I have fixed the two major problems with the rendering of the list of terms document. 

1. There was indeed a missing open `<tr>` tag, fixed here: https://github.com/tdwg/dwc/commit/d26027826ab5dab04059c5df69d169823d60075b#r41447758
2. The bad rendering of some of the index sections appears to have been caused by unwanted trailing vertical bars. I changed the way the code removed the last trailing `|` and they are now gone from the output Markdown file.

Can you check the rendering of the [new output file](https://github.com/tdwg/dwc/blob/fix_list_of_terms_build_script/docs/list/index.md) to verify that these problems are gone and if so, merge this pull request and close https://github.com/tdwg/dwc/issues/270 ?

### CODE REVIEW

**Comment by baskaufs** [comment]
Actually, while we are fixing stuff, I updated my affiliation.

**Comment by tucotuco** [comment]
Should we expect these to resolve yet?

http://rs.tdwg.org/dwc/doc/list/2020-08-12
http://rs.tdwg.org/version/dwc/2020-08-12
http://rs.tdwg.org/dwc/terms/version/month-2020-08-12

**Comment by baskaufs** [comment]
Not yet. I need to manually add the document information to rs.tdwg.org since there isn't a way to automate that yet. Then Matt Blissett needs to trigger a reloading of the data. I was hoping to work on that this afternoon, but got distracted with other stuff.

**Comment by peterdesmet** [comment]
Renders ok, `<tr>` gone

**Pull request merged**
