### PR TITLE
add verticalDatum , move measurementValue

### PR DESCRIPTION
**Pull request by baskaufs**
@tucotuco I think the only changes required here were to add the new term `verticalDatum` and to move `measurementValue` from the table saying it should only have literal values, to the table that says there is an IRI analog. The other `dwciri:` changes [here](https://github.com/tdwg/rs.tdwg.org/blob/master/process/dwc-revisions/dwc-revisions-2021-07-15/iri_2021-07-15.csv) were changes to terms that were already properly placed in the tables. 

I scanned through the milestone to check there as well and I didn't see anything else obvious, but you should double-check me.

### CODE REVIEW

**Comment by baskaufs** [comment]
Satisfies #341

**Comment by baskaufs** [comment]
I forgot about the chrono IRI terms, so we shouldn't merge this until I finish that 
https://github.com/tdwg/chrono/issues/12

**Comment by baskaufs** [comment]
@tucotuco I've made a first pass at adding a chronoiri table. You can see how it looks [here](https://github.com/tdwg/dwc/blob/update_rdf_guide/docs/rdf/index.md#39-chronometric-age-extension-chrono-terms-that-have-analogues-in-the-chronoiri-namespace-normative)

**Comment by tucotuco** [comment]
I have done a semi-thorough review of the revised RDF document and have the following observations:

It looks like verticalDatum and measurementValue are the only dwciri: term additions based on [this list of new terms](https://github.com/tdwg/dwc/issues?q=is%3Aissue+is%3Aopen++label%3A%22Term+-+add%22+label%3A%22Process+-+implement%22+). 

In Section 3.4, I think verbatimIdentification should be in the list in the set that includes verbatimEventDate and has the comment in the right-hand column, "Based on their term definitions, these terms are expected to have untyped literal values".  By the way, while you're there, that sentence could use a period. 

In Section 3.5, I think the new Taxon terms need to be added in the second set of terms for Identifications. These should be subfamily, genericName, infragenericEpithet, and cultivarEpithet.

References to ISO 8601:2004(E) should be changed to ISO 8601-1:2019. 

Should the newly included dwciri:measurementValue be included in Example 31 for the sake of completeness?

In Section 3.3 the part about dcterms:type is outdated. Based on actual usage of the term in practice, dc:type was recommended in place of dcterms:type for Darwin Core. Although maybe it is OK to leave that one, as dcterms:type would still be recommended for non-literal objects.

I think that's it.

**Comment by baskaufs** [comment]
Oh, good catch! I was only thinking about adding the new IRI analogs, but wasn't thinking about the new terms that needed to be listed in the tables for NO IRI analog. I've added them now.

I changed the references to ISO 8601 to the new version.

I had thought about adding `dwciri:measurementValue` to Example 31, but it didn't fit into the existing example, which had a literal numeric value. I think it probably needs a separate example, but I wasn't sure enough about what kind of values to use with what kind of subject, so I just dodged it for now.

I think the info in section 3.3 is still OK. It doesn't really make any statement about preferred use, but just says if you use a literal value that you should use the dc: analog, which is the normal practice. 

If this looks good, maybe go ahead and merge. Since I'm going to go through the RDF guide for RFC 2119 keywords, I'll be giving it another read-through when my eyes are fresh and will hopefully catch anything we missed.

**Comment by tucotuco** [comment]
Yay, on to RFC 2119 keywords!

**Pull request merged**
