### PR TITLE
Remove UseWithIRI from the "normative document"

### PR DESCRIPTION
**Pull request by baskaufs**
I don't think tdwgutility:UseWithIRI should be included with the other DwC terms.  We decided that the management of tdwgutility: (http://rs.tdwg.org/dwc/terms/attributes/) should be outside of DwC, since it has become a TDWG-wide utility namespace.  Currently the data for it is in the https://github.com/tdwg/rs.tdwg.org/blob/master/utility/utility.csv file (although I need to correct the capitalization for "Iri" as we discussed.

### CODE REVIEW

**Comment by peterdesmet** [comment]
I agree, but there are two things that need to be resolved:

1. This "term" needs to be removed from /build/config/terms.csv as well (currently generates a build error because of that)
2. We need some way to group these `dwc:iri` terms on the quick ref guide, otherwise they will appear as being listed under the last class (`resourceRelationShip`):

screen shot 2017-10-23 at 10 40 35

@stijnvanhoey any idea for the latter. How did we do this for the record-level terms?

**Comment by baskaufs** [comment]
I think it is fine to use tdwgutility:UseWithIRI to group the dwciri: terms.  That's what we made it up for.  But does it have to be defined in a line in the normative document itself in order to use it?  Can't it be a value of the "organized_in" column in /build/config/terms.csv without being the subject of line in the normative CSV itself.  I don't understand that.

**Comment by peterdesmet** [comment]
> But does it have to be defined in a line in the normative document itself in order to use it?

Ideally no, but that how the build script is set up for the moment. We need to rethink that.

**Comment by tucotuco** [comment]
Is this still on the table? The term currently has the identifier http://rs.tdwg.org/dwc/terms/attributes/UseWithIRI.

**Comment by peterdesmet** [comment]
I’ll let @baskaufs decide this one

**Comment by tucotuco** [comment]
Yes, the idea is clear and makes sense. What are the steps needed to get
that term into the right namespace and yet use it in the Quick Reference
Guide? Isn't it ok to have the term (with corrected namespace) in the
normative document in much the same way that the Dublin Core terms are in
there? By being in the normative document we are only really saying that we
use it in Darwin Core, no?

**Comment by baskaufs** [comment]
So here is what the tdwgutility: namespace page will look like if/when the term dereferencing is enabled: http://rs-test.tdwg.org/dwc/terms/attributes/ .  As you can see, I took the liberty to add additional terms that were needed to categorized Audubon Core terms in the same way we minted the "UseWithIRI" class for Darwin Core.  The information at the top of the page makes it clear that these terms aren't part of any TDWG standard - the abstract says "This list includes terms necessary to describe various TDWG vocabularies.", which is an accurate description of their purpose.  It's an unofficial "utility" class that we use to mint any terms we need.

As far as being in the "normative" document, I don't think any of the tdwgutility: namespace terms should be there.  Do they have to be there in order to generate the quick reference guide?  Essentially we are removing http://rs.tdwg.org/dwc/terms/attributes/ from Darwin Core, although it's not clear that it ever was officially "in" Darwin Core anyway.  We are now at the point (finally) of being clear about what's in and out of Darwin Core.  Terms are in Darwin Core when we say they are in the metadata of their term list (as in http://rs-test.tdwg.org/dwc/dcterms/).  Things are not in Darwin Core when we say that they are not part of any standard (as the tdwgutility: term list now does).  

Additionally, when the Darwin Core vocabulary URI is dereferenced, it states clearly which term lists are part of Darwin Core (see http://rs-test.tdwg.org/dwc/).  Any term list not there (such as the tdwgutility: terms) is NOT part of the Darwin Core vocabulary.  

This is a part of the whole concept embodied in the Standards Documentation Specification that we get away from the idea of thinking that some particular document defines a vocabulary.  Rather, we use metadata to tell people what's part of a standard and what's not, and what's normative and what's not.  Despite the utility of having a single document like https://github.com/tdwg/dwc/blob/master/vocabulary/term_versions.csv, I really don't like calling it "the normative document".  There is no explanatory metadata in that document saying what the document is and what is the significance of the data that's included.  That's in contrast to both the human-readable documents I referenced above and machine-readable documents like http://rs-test.tdwg.org/dwc/dcterms.ttl and http://rs-test.tdwg.org/dwc.ttl which lay out clearly what's in the vocabulary.

**Comment by peterdesmet** [comment]
@baskaufs @tucotuco so, `useWithIRI` is still in `term_versions.csv`:

https://github.com/tdwg/dwc/blob/82807f9e789cc2b77f378704867a4e5778ed28a6/vocabulary/term_versions.csv#L197

It is used to group terms on the quick ref guide, but the "class" is not displayed. Is it fine to keep it in `term_versions` i.e. can this pull request be closed without merging?

**Comment by baskaufs** [comment]
So I think that this is related to Issue #239 .  What does it mean when we say "Normative document: a CSV file with the full version history of Darwin Core terms" on the [landing page](https://dwc.tdwg.org/)?  To me, that says that everything on that list is a version of a Darwin Core term.  I don't think that tdwgutility:UseWithIRI is a Darwin Core term, so it shouldn't be on that list.  But then there are also other versions of old terms that were never part of the ratified Darwin Core.  They probably shouldn't be on the list either.  Basically, I think calling that CSV file the "normative document" is misleading.  I'm not exactly sure what it is, but whatever it is, we need to do a better job of explaining it.

One of the major purposes of the Standards Documentation Specification was to make it possible for people to know exactly what is and is not part of every standard, and what parts of all standards are normative.  We are not there yet with Darwin Core.

**Pull request closed without merging**
