### PR TITLE
Add citation information to QRG.

### PR DESCRIPTION
**Pull request by tucotuco**

### CODE REVIEW

**Comment by peterdesmet** [comment]
Updated formatting. Looks good to me. @baskaufs do you want to approve this?

**Review by baskaufs — COMMENTED** [review]
I got some feedback from Jonathan Rees about the recommended citation for the list of terms document and he was noting that if documents were versioned, the specific version should be cited so that people could look up the exact version to see what was included in the document *at that time*. For example, it should be:

```
Darwin Core Maintenance Group. 2020. List of Darwin Core terms. Biodiversity Information Standards (TDWG). http://rs.tdwg.org/dwc/doc/list/2020-08-20
```
rather than

```
Darwin Core Maintenance Group. 2020. List of Darwin Core terms. Biodiversity Information Standards (TDWG). http://rs.tdwg.org/dwc/doc/list/
```

So I've been trying to adopt that approach every time we generate a new version and you can actually track the versions of the list of terms document back through time by clicking on the version IRI links. 

However, since the QRG isn't really an official standards document, we've been avoiding mucking it up with the official header stuff that we use with the standards document. That makes it cleaner and less intimidating. As a consequence, we don't really include version information or anything like that with the document.

Honestly, I think that no one should be citing the QRG. If they want to cite something, let them cite the list of terms document, which has the full, authoritative metadata and includes everything that's in the QRG and more. So it makes more sense to me to tell people that they should be citing the list of terms document, rather than telling them how to cite the QRG.

**Comment by tucotuco** [comment]
Made the changes suggested by @baskaufs Proceed with merge if you agree.

**Comment by peterdesmet** [comment]
Ok, will merge. Note to @baskaufs: the citation is now /list, not /list/yyyy-mm-dd. If you think people should list the version (with that) then I'd have to find a way to get that automatically for this page.

**Review by peterdesmet — APPROVED** [review]

**Comment by baskaufs** [comment]
Hmm. Well, as I said, I'm not sure why people would necessarily want to cite the QRG, at least as any kind of source where the version would be important (e.g. to say what the definition of a term was at a certain point in time). I can see why people might want to refer people to it as a tool, and in that case, the generic URL would probably be good enough.

**Pull request merged**
