### PR TITLE
Added new terms for Sampling Events based on Decision-2015-03-19_18.

### PR DESCRIPTION
**Pull request by tucotuco**
Anyone care to check my work and merge with master?

### CODE REVIEW

**Comment by mdoering** [comment]
Looks good, cant see anything wrong!

**Comment by tucotuco** [comment]
I merged, but the changes do not appear on rs.tdwg.org/dwc. Is there
another step that has to be done?

**Comment by mdoering** [comment]
the branch that is exposed on github pages is the gh-pages branch. We need to merge the change there too

**Comment by mdoering** [comment]
Also added to gbif dwc-api enumerations: https://github.com/gbif/dwc-api/commit/4fff482f71ab1fdb7a3a63d81f34b39ec660ff19

**Pull request merged**
