### PR TITLE
Separate examples with `;` and style

### PR DESCRIPTION
**Pull request by tucotuco**
Note that the build.py script was not run before the most recent commit and will have to be before deployment.

### CODE REVIEW

**Comment by peterdesmet** [comment]
I have now updated the `terms.tmpl` to style the examples on newlines, making them much more readable:

Screenshot 2023-04-26 at 13 17 02

@tucotuco @baskaufs Note: all changes were done in `terms.tmpl` + `custom.css`, not in the build script. Other build scripts that make use of the template don't require an update, just a rerun to change their output. 👍 

## Todo

1. @tucotuco can you make some corrections to the following examples:

    - [ ] associatedTaxa: missed a comma
    - [ ] parentEventID: comma should remain
    - [ ] footprintSRS: probably correct if the intent to have 2 examples
    - [ ] identificationQualifier: wrap the sentences starting with "for" in parenthesis, which is the commonly used way of clarifying a value
    - [ ] recordedByID: stray . at the end
    - [ ] organismQuantityType: maybe add the `many` examples as in organismQuantity
    - [ ] identifiedByID: missed a comma, remove the . at the end
    - [ ] infragenericEpithet: unclosed parenthesis in first example

- @tucotuco (or me) run `build/build.py` to update `docs/terms/index.md` once above is corrected.
- @baskaufs run `build/build-termlist.py`. For me this resulted in a CERTIFICATE_VERIFY_FAILED error. Can you or @tucotuco try to run this?

**Review by peterdesmet — CHANGES_REQUESTED** [review]
See todo

**Comment by baskaufs** [comment]
@peterdesmet The build-termlist.py script doesn't use the template, so I don't think there's anything to be gained by re-running it. I think it should be easy to fix, though by just doing a replacement of semicolon characters with newline characters. I will put this on my to-do list, but I don't think it should block this.

**Comment by peterdesmet** [comment]
@baskaufs for the QRG a bit more is going on than replacing `;` with newline (it's using unnumbered lists in case of multiple examples). But the list doesn't necessarily need to use the same approach (maybe the ; can just remain there). I agree on the timing.

**Comment by tucotuco** [comment]
@peterdesmet You should be a copy editor if you are not already. Aside from footprintSRS, which should have two examples, I have made and committed the changes.

To run build-termlist.py effectively, the updated term_versions.csv file has to be merged into master and then run the script, as it gets its information from GitHub.

**Comment by peterdesmet** [comment]
Thanks John! I made a few stylistic changes to be consistent, e.g. referring to values as `value` but to terms as scientificName (no backticks). I did this in:

- Examples, see https://github.com/tdwg/dwc/pull/443/commits/5b671332c256e531269dfbcd147354db79ce51a3
- Comments (!), see https://github.com/tdwg/dwc/pull/443/commits/c6913c080f904a2c3b523462ee738a52c525283e

Please review. The commits contain the changes to csv and index.md, as well as a commit description.

**Comment by tucotuco** [comment]
The styling changes look OK to me.

**Review by peterdesmet — APPROVED** [review]

**Pull request merged**
