### PR TITLE
Use term name as label name

### PR DESCRIPTION
**Pull request by peterdesmet**
We currently use the **local name** of a term (e.g. in the quick reference guide, such as `scientificNameAuthorship`), which is a bit of a weird concept. It would be better to use the **label**, which is a concept that is part of the standard. The current labels use spaces (e.g. `Scientific Name Authorship`), which was a [2011 decision](http://rs.tdwg.org/dwc/terms/history/decisions/index.htm#Decision-2011-10-16_5):

> The label for all terms have been changed to words in English rather than lower camel case term names. This will facilitate discovery with search engines and is consistent with Dublin Core.

In my experience, those labels are not used for Darwin Core (they are also not in the quick reference guide). People refer to terms by their local name, which are also in English. I therefore propose to update the labels to what is currently the local name and start using the labels. If someone still wants a space separated version, that is fairly easy to generate.

In this pull request I have update the label column with the last element of the `term_iri`, e.g.:

`http://rs.tdwg.org/dwc/terms/associatedReferences` -> label: `associatedReferences`

## Note 1

I kept the capitalization of the IRI. For some terms this has changed over time, e.g.:

* `Class`: http://digir.net/schema/conceptual/darwin/2003/1.0/Class (superseded)
* `Class`: http://digir.net/schema/conceptual/darwin/2003/1.0/Class (deprecated)
* `Class`: http://rs.tdwg.org/dwc/dwcore/Class (deprecated)
* `class`: http://rs.tdwg.org/dwc/terms/class (superseded)
* `class`: http://rs.tdwg.org/dwc/terms/class (recommended)

## Note 2

This transformation didn't change any label names (except for removing spaces and different capitalization) except for:

old label | new label | term_iri
--- | --- | ---
Darwin Core Type | DwCType | http://rs.tdwg.org/dwc/terms/DwCType
Event Attribute | EventAttributeValue | http://rs.tdwg.org/dwc/terms/EventAttributeValue
Sample Attribute ID | SamplingAttributeID | http://rs.tdwg.org/dwc/terms/SamplingAttributeID
Sample Attribute Type | SamplingAttributeType | http://rs.tdwg.org/dwc/terms/SamplingAttributeType

But I think all of these are correct updates.

### CODE REVIEW

**Comment by baskaufs** [comment]
What we are proposing to do here is to change the metadata of the terms (that is, the terms as a continuing entity).  Any time you change the metadata of a term, you are generating a new version of that term.  So we should not be changing the labels of term versions issued in 2009 or 2015.  We should be generating new term versions that have an issued date of 2017-10-02.  For example:

Existing line:
Country Code,2009-04-24,recommended,http://rs.tdwg.org/dwc/terms/countryCode,http://rs.tdwg.org/dwc/terms/version/countryCode-2009-04-24,,http://www.w3.org/1999/02/22-rdf-syntax-ns#Property,The standard code for the country in which the Location occurs.

Added line:
countryCode,2017-10-02,recommended,http://rs.tdwg.org/dwc/terms/countryCode,http://rs.tdwg.org/dwc/terms/version/countryCode-2017-10-02,,http://www.w3.org/1999/02/22-rdf-syntax-ns#Property,The standard code for the country in which the Location occurs.

We should never change any existing line in the table - only add lines.  Otherwise we are changing history.

**Comment by baskaufs** [comment]
Oh, and we should only be doing this for terms whose most recent versions have the status "recommended" (the other versions are dead and can't change).  Actually, this also changes the status of the previously recommended version to "superseded", so the changed existing line and the new line should look like this:

Country Code,2009-04-24,superseded,http://rs.tdwg.org/dwc/terms/countryCode,http://rs.tdwg.org/dwc/terms/version/countryCode-2009-04-24,,http://www.w3.org/1999/02/22-rdf-syntax-ns#Property,The standard code for the country in which the Location occurs.
countryCode,2017-10-02,recommended,http://rs.tdwg.org/dwc/terms/countryCode,http://rs.tdwg.org/dwc/terms/version/countryCode-2017-10-02,,http://www.w3.org/1999/02/22-rdf-syntax-ns#Property,The standard code for the country in which the Location occurs.

So what I said before wasn't exactly true.  You can change a preciously existing term version in one way: changing its status from "recommended" to "superseded".

**Comment by peterdesmet** [comment]
Fair enough, I can implement it that way. Any feedback on the proposed change?

**Comment by tucotuco** [comment]
Good catch, Steve. Since there are a large number of changes where the
recommendations got pulled out and into comments, which are no longer in
the term metadata, it's not a bad idea to go ahead and use the opportunity
to change all terms (because of the label change).

With the term local name as the preferred label, we solve having a metadata
element that gives us a standard field name (column header, etc.) and begs
that english labels go with labels in every other language. That seems like
a good thing to me.

**Comment by tucotuco** [comment]
We need to do this differently and will make a new pull request.

**Pull request closed without merging**
